import React, { createContext, useContext, useState } from 'react';

const translations = {
    en: {
        // Sidebar
        modules: 'Modules',
        telemetry: 'Telemetry & Diagnostics',
        command: 'Madurai Command Center',
        pathogen: 'Pathogen & Vector Radar',
        inventory: 'Bio-Supply Inventory',
        settings: 'Settings',
        about: 'About',
        bot: 'Mei Arivu Bot',
        maduraiDistrict: 'Madurai District',
        smartCity: 'Smart City Waste Intelligence Platform',

        // Page titles & subtitles
        telemetryTitle: 'Telemetry & Diagnostics',
        telemetrySub: 'Single-pile bioremediation analysis powered by ML',
        commandTitle: 'Madurai Command Center',
        commandSub: 'City-wide geospatial waste intelligence for Madurai District',
        pathogenTitle: 'Pathogen & Vector Radar',
        pathogenSub: 'Predictive vector breeding & public health risk engine',
        inventoryTitle: 'Bio-Supply Inventory',
        inventorySub: 'Biological supply chain tracking & auto-procurement',
        settingsTitle: 'Settings',
        settingsSub: 'Language, appearance, profile & security configuration',
        aboutTitle: 'About',
        aboutSub: 'Platform info, team, tech stack & contact details',
        botTitle: 'Mei Arivu Assistant',
        botSub: 'App Help & AI Guide',

        // Telemetry
        telemetryInput: 'Telemetry Input',
        temperature: 'Temperature (°C)',
        moisture: 'Moisture (%)',
        phLevel: 'pH Level',
        cnRatio: 'C:N Ratio',
        wasteType: 'Waste Type',
        analyzeStack: 'Analyze Stack',
        analyzing: 'Analyzing...',
        awaitingTelemetry: 'Awaiting Telemetry',
        awaitingDesc: 'Use the input panel to supply environmental parameters for ML evaluation.',
        diagnosticOverview: 'Diagnostic Overview',
        analysisComplete: 'Analysis Complete',
        estBioremediation: 'Est. Bioremediation',
        days: 'Days',
        health: 'Health',
        requiredAction: 'Required Action Directive',

        // Command Center
        totalActiveSites: 'Total Active Sites',
        wasteBacklog: 'Waste Backlog',
        avgDegradation: 'Avg. Degradation',
        alertsActive: 'Alerts Active',
        liveGeospatial: 'Madurai District — Live Geospatial Feed',
        activeBioSites: 'Active Bioremediation Sites',
        cityWasteBacklog: 'City-Wide Waste Backlog',

        // Pathogen
        vectorAlert: 'Vector Breeding Alert',
        highRiskZones: 'High-Risk Zones Detected',
        vectorAlertDesc: 'Waste piles with moisture >70% and temperature 30–40°C sustained for over 5 days have been flagged as severe vector breeding grounds. Immediate anti-larval spraying recommended.',
        highRiskRegistry: 'High Risk Zone Registry',
        zone: 'Zone',
        temp: 'Temp',
        risk: 'Risk',
        threat: 'Threat',
        weeklyTrend: 'Weekly Incident Trend',
        emergencyActions: 'Emergency Actions',
        emergencyDesc: 'Dispatch an automated alert to the Madurai Municipal Health Department for immediate anti-larval spraying operations in the flagged zones.',
        alertHealth: 'Alert Madurai Health Department',
        alertDispatched: 'Alert Dispatched to Health Dept.',
        dengueZones: 'Dengue Zones',
        malariaZone: 'Malaria Zone',

        // Inventory
        totalItems: 'Total Items',
        critical: 'Critical',
        lowStock: 'Low Stock',
        inventoryValue: 'Inventory Value',
        bioSupplyRegistry: 'Bio-Supply Chain Registry',
        autoReorderNote: 'Auto-reorder at <20% capacity',
        material: 'Material',
        category: 'Category',
        stockLevel: 'Stock Level',
        status: 'Status',
        supplier: 'Supplier',
        action: 'Action',
        autoReorder: 'Auto-Reorder',
        ordered: 'Ordered',
        processing: 'Processing...',

        // Settings
        langRegion: 'Language & Region',
        langDesc: 'Choose display language for the platform interface',
        appearance: 'Appearance',
        appearanceDesc: 'Customize the visual theme of your dashboard',
        userProfile: 'User Profile',
        profileDesc: 'Your personal and organizational details',
        editProfile: 'Edit Profile',
        saveChanges: 'Save Changes',
        fullName: 'Full Name',
        designation: 'Designation',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        department: 'Department',
        location: 'Location',
        notifications: 'Notifications',
        notifDesc: 'Control how you receive alerts and updates',
        emailNotif: 'Email Notifications',
        emailNotifDesc: 'Receive daily digests and critical alerts via email',
        smsAlerts: 'SMS Alerts',
        smsAlertsDesc: 'Get text messages for high-priority warnings',
        browserPush: 'Browser Push',
        browserPushDesc: 'Real-time browser push notifications',
        healthAlerts: 'Health Department Alerts',
        healthAlertsDesc: 'Automatic forwarding to Madurai Municipal Health Dept',
        loginSecurity: 'Login & Security',
        loginSecDesc: 'Account access and authentication settings',
        password: 'Password',
        passwordDesc: 'Last changed 14 days ago',
        change: 'Change',
        twoFactor: 'Two-Factor Authentication',
        twoFactorDesc: 'Add an extra layer of security to your account',
        enabled: 'Enabled',
        activeSessions: 'Active Sessions',
        activeSessionsDesc: '1 active session on this device',
        loginHistory: 'Login History',
        loginHistoryDesc: 'Last login: Today at 18:46 IST from Madurai',
        viewAll: 'View All',
        signOut: 'Sign Out of All Devices',
    },
    ta: {
        modules: 'தொகுதிகள்',
        telemetry: 'தொலைஅளவை & நோயறிதல்',
        command: 'மதுரை கட்டுப்பாட்டு மையம்',
        pathogen: 'நோய்க்கிருமி & திசை ரேடார்',
        inventory: 'உயிர்-விநியோக சரக்கு',
        settings: 'அமைப்புகள்',
        about: 'பற்றி',
        bot: 'மே அறிவு பாட்',
        maduraiDistrict: 'மதுரை மாவட்டம்',
        smartCity: 'ஸ்மார்ட் சிட்டி கழிவு நுண்ணறிவு தளம்',

        telemetryTitle: 'தொலைஅளவை & நோயறிதல்',
        telemetrySub: 'ML மூலம் ஒற்றை-குவியல் உயிர்சீரமைப்பு பகுப்பாய்வு',
        commandTitle: 'மதுரை கட்டுப்பாட்டு மையம்',
        commandSub: 'மதுரை மாவட்டத்திற்கான நகர அளவிலான புவிவெளி கழிவு நுண்ணறிவு',
        pathogenTitle: 'நோய்க்கிருமி & திசை ரேடார்',
        pathogenSub: 'முன்கணிப்பு வெக்டர் இனப்பெருக்கம் & பொது சுகாதார ஆபத்து இயந்திரம்',
        inventoryTitle: 'உயிர்-விநியோக சரக்கு',
        inventorySub: 'உயிரியல் விநியோக சங்கிலி கண்காணிப்பு & தானியங்கி கொள்முதல்',
        settingsTitle: 'அமைப்புகள்',
        settingsSub: 'மொழி, தோற்றம், சுயவிவரம் & பாதுகாப்பு கட்டமைப்பு',
        aboutTitle: 'பற்றி',
        aboutSub: 'தள தகவல், குழு, தொழில்நுட்ப அடுக்கு & தொடர்பு விவரங்கள்',
        botTitle: 'மே அறிவு உதவியாளர்',
        botSub: 'பயன்பாட்டு உதவி & AI வழிகாட்டி',

        telemetryInput: 'தொலைஅளவை உள்ளீடு',
        temperature: 'வெப்பநிலை (°C)',
        moisture: 'ஈரப்பதம் (%)',
        phLevel: 'pH நிலை',
        cnRatio: 'C:N விகிதம்',
        wasteType: 'கழிவு வகை',
        analyzeStack: 'குவியல் பகுப்பாய்வு',
        analyzing: 'பகுப்பாய்வு...',
        awaitingTelemetry: 'தொலைஅளவை காத்திருக்கிறது',
        awaitingDesc: 'ML மதிப்பீட்டிற்கு சுற்றுச்சூழல் அளவுருக்களை வழங்கவும்.',
        diagnosticOverview: 'நோயறிதல் மேலோட்டம்',
        analysisComplete: 'பகுப்பாய்வு முடிந்தது',
        estBioremediation: 'மதிப்பிடப்பட்ட உயிர்சீரமைப்பு',
        days: 'நாட்கள்',
        health: 'ஆரோக்கியம்',
        requiredAction: 'தேவையான நடவடிக்கை உத்தரவு',

        totalActiveSites: 'மொத்த செயலில் தளங்கள்',
        wasteBacklog: 'கழிவு பின்னடைவு',
        avgDegradation: 'சராசரி சிதைவு',
        alertsActive: 'எச்சரிக்கைகள் செயலில்',
        liveGeospatial: 'மதுரை மாவட்டம் — நேரடி புவிவெளி ஊட்டம்',
        activeBioSites: 'செயலில் உள்ள உயிர்சீரமைப்பு தளங்கள்',
        cityWasteBacklog: 'நகர அளவிலான கழிவு பின்னடைவு',

        vectorAlert: 'வெக்டர் இனப்பெருக்க எச்சரிக்கை',
        highRiskZones: 'அதிக ஆபத்து மண்டலங்கள் கண்டறியப்பட்டன',
        vectorAlertDesc: 'ஈரப்பதம் >70% மற்றும் வெப்பநிலை 30–40°C 5 நாட்களுக்கு மேல் நிலைத்திருக்கும் கழிவு குவியல்கள் கடுமையான வெக்டர் இனப்பெருக்க மையங்களாக கொடியிடப்பட்டுள்ளன.',
        highRiskRegistry: 'அதிக ஆபத்து மண்டல பதிவேடு',
        zone: 'மண்டலம்',
        temp: 'வெப்ப.',
        risk: 'ஆபத்து',
        threat: 'அச்சுறுத்தல்',
        weeklyTrend: 'வாராந்திர சம்பவ போக்கு',
        emergencyActions: 'அவசர நடவடிக்கைகள்',
        emergencyDesc: 'கொடியிடப்பட்ட மண்டலங்களில் உடனடி லார்வா எதிர்ப்பு தெளிப்பு நடவடிக்கைகளுக்கு மதுரை நகராட்சி சுகாதாரத் துறைக்கு தானியங்கி எச்சரிக்கையை அனுப்பவும்.',
        alertHealth: 'மதுரை சுகாதாரத் துறையை எச்சரிக்கவும்',
        alertDispatched: 'சுகாதாரத் துறைக்கு எச்சரிக்கை அனுப்பப்பட்டது',
        dengueZones: 'டெங்கு மண்டலங்கள்',
        malariaZone: 'மலேரியா மண்டலம்',

        totalItems: 'மொத்த பொருட்கள்',
        critical: 'முக்கியமான',
        lowStock: 'குறைந்த இருப்பு',
        inventoryValue: 'சரக்கு மதிப்பு',
        bioSupplyRegistry: 'உயிர்-விநியோக சங்கிலி பதிவேடு',
        autoReorderNote: '<20% கொள்ளளவில் தானியங்கி மறு ஆர்டர்',
        material: 'பொருள்',
        category: 'வகை',
        stockLevel: 'இருப்பு நிலை',
        status: 'நிலை',
        supplier: 'சப்ளையர்',
        action: 'நடவடிக்கை',
        autoReorder: 'தானியங்கி ஆர்டர்',
        ordered: 'ஆர்டர் செய்யப்பட்டது',
        processing: 'செயலாக்கம்...',

        langRegion: 'மொழி & பகுதி',
        langDesc: 'தளத்தின் காட்சி மொழியை தேர்வு செய்யவும்',
        appearance: 'தோற்றம்',
        appearanceDesc: 'உங்கள் டாஷ்போர்டின் காட்சி தீம் தனிப்பயனாக்கவும்',
        userProfile: 'பயனர் சுயவிவரம்',
        profileDesc: 'உங்கள் தனிப்பட்ட மற்றும் நிறுவன விவரங்கள்',
        editProfile: 'சுயவிவரத்தை திருத்து',
        saveChanges: 'மாற்றங்களை சேமி',
        fullName: 'முழு பெயர்',
        designation: 'பதவி',
        emailAddress: 'மின்னஞ்சல் முகவரி',
        phoneNumber: 'தொலைபேசி எண்',
        department: 'துறை',
        location: 'இடம்',
        notifications: 'அறிவிப்புகள்',
        notifDesc: 'எச்சரிக்கைகள் மற்றும் புதுப்பிப்புகளை எவ்வாறு பெறுவது',
        emailNotif: 'மின்னஞ்சல் அறிவிப்புகள்',
        emailNotifDesc: 'மின்னஞ்சல் வழியாக தினசரி சுருக்கங்களையும் முக்கிய எச்சரிக்கைகளையும் பெறவும்',
        smsAlerts: 'SMS எச்சரிக்கைகள்',
        smsAlertsDesc: 'உயர் முன்னுரிமை எச்சரிக்கைகளுக்கு குறுஞ்செய்திகள் பெறவும்',
        browserPush: 'உலாவி புஷ்',
        browserPushDesc: 'நிகழ்நேர உலாவி புஷ் அறிவிப்புகள்',
        healthAlerts: 'சுகாதாரத் துறை எச்சரிக்கைகள்',
        healthAlertsDesc: 'மதுரை நகராட்சி சுகாதாரத் துறைக்கு தானியங்கி அனுப்புதல்',
        loginSecurity: 'உள்நுழைவு & பாதுகாப்பு',
        loginSecDesc: 'கணக்கு அணுகல் மற்றும் அங்கீகார அமைப்புகள்',
        password: 'கடவுச்சொல்',
        passwordDesc: '14 நாட்களுக்கு முன் மாற்றப்பட்டது',
        change: 'மாற்று',
        twoFactor: 'இரு-காரணி அங்கீகாரம்',
        twoFactorDesc: 'உங்கள் கணக்கிற்கு கூடுதல் பாதுகாப்பு அடுக்கை சேர்க்கவும்',
        enabled: 'இயக்கப்பட்டது',
        activeSessions: 'செயலில் அமர்வுகள்',
        activeSessionsDesc: 'இந்த சாதனத்தில் 1 செயலில் அமர்வு',
        loginHistory: 'உள்நுழைவு வரலாறு',
        loginHistoryDesc: 'கடைசி உள்நுழைவு: இன்று 18:46 IST மதுரையிலிருந்து',
        viewAll: 'அனைத்தையும் காண்',
        signOut: 'எல்லா சாதனங்களிலிருந்தும் வெளியேறு',
    },
    hi: {
        modules: 'मॉड्यूल',
        telemetry: 'टेलीमेट्री & डायग्नोस्टिक्स',
        command: 'मदुरै कमांड सेंटर',
        pathogen: 'रोगजनक & वेक्टर रडार',
        inventory: 'बायो-सप्लाई इन्वेंटरी',
        settings: 'सेटिंग्स',
        about: 'के बारे में',
        bot: 'मेई अरिवु बॉट',
        maduraiDistrict: 'मदुरै जिला',
        smartCity: 'स्मार्ट सिटी अपशिष्ट इंटेलिजेंस प्लेटफ़ॉर्म',

        telemetryTitle: 'टेलीमेट्री & डायग्नोस्टिक्स',
        telemetrySub: 'ML द्वारा संचालित सिंगल-पाइल बायोरेमेडिएशन विश्लेषण',
        commandTitle: 'मदुरै कमांड सेंटर',
        commandSub: 'मदुरै जिले के लिए शहर-व्यापी भू-स्थानिक अपशिष्ट इंटेलिजेंस',
        pathogenTitle: 'रोगजनक & वेक्टर रडार',
        pathogenSub: 'भविष्यवाणी वेक्टर प्रजनन & सार्वजनिक स्वास्थ्य जोखिम इंजन',
        inventoryTitle: 'बायो-सप्लाई इन्वेंटरी',
        inventorySub: 'जैविक आपूर्ति श्रृंखला ट्रैकिंग & ऑटो-प्रोक्योरमेंट',
        settingsTitle: 'सेटिंग्स',
        settingsSub: 'भाषा, दिखावट, प्रोफ़ाइल & सुरक्षा कॉन्फ़िगरेशन',
        aboutTitle: 'के बारे में',
        aboutSub: 'प्लेटफ़ॉर्म जानकारी, टीम, तकनीकी स्टैक और संपर्क विवरण',
        botTitle: 'मेई अरिवु सहायक',
        botSub: 'ऐप सहायता और एआई गाइड',

        telemetryInput: 'टेलीमेट्री इनपुट',
        temperature: 'तापमान (°C)',
        moisture: 'नमी (%)',
        phLevel: 'pH स्तर',
        cnRatio: 'C:N अनुपात',
        wasteType: 'अपशिष्ट प्रकार',
        analyzeStack: 'स्टैक विश्लेषण',
        analyzing: 'विश्लेषण हो रहा है...',
        awaitingTelemetry: 'टेलीमेट्री की प्रतीक्षा',
        awaitingDesc: 'ML मूल्यांकन के लिए पर्यावरणीय पैरामीटर प्रदान करें।',
        diagnosticOverview: 'डायग्नोस्टिक ओवरव्यू',
        analysisComplete: 'विश्लेषण पूर्ण',
        estBioremediation: 'अनुमानित बायोरेमेडिएशन',
        days: 'दिन',
        health: 'स्वास्थ्य',
        requiredAction: 'आवश्यक कार्रवाई निर्देश',

        totalActiveSites: 'कुल सक्रिय साइट',
        wasteBacklog: 'अपशिष्ट बैकलॉग',
        avgDegradation: 'औसत गिरावट',
        alertsActive: 'सक्रिय अलर्ट',
        liveGeospatial: 'मदुरै जिला — लाइव भू-स्थानिक फ़ीड',
        activeBioSites: 'सक्रिय बायोरेमेडिएशन साइट',
        cityWasteBacklog: 'शहर-व्यापी अपशिष्ट बैकलॉग',

        vectorAlert: 'वेक्टर प्रजनन अलर्ट',
        highRiskZones: 'उच्च-जोखिम क्षेत्र पाए गए',
        vectorAlertDesc: 'नमी >70% और तापमान 30-40°C 5 दिनों से अधिक बनी रहने वाली अपशिष्ट ढेरों को गंभीर वेक्टर प्रजनन स्थलों के रूप में चिह्नित किया गया है।',
        highRiskRegistry: 'उच्च जोखिम क्षेत्र रजिस्ट्री',
        zone: 'क्षेत्र',
        temp: 'तापमान',
        risk: 'जोखिम',
        threat: 'खतरा',
        weeklyTrend: 'साप्ताहिक घटना प्रवृत्ति',
        emergencyActions: 'आपातकालीन कार्रवाई',
        emergencyDesc: 'चिह्नित क्षेत्रों में तत्काल लार्वा-रोधी छिड़काव के लिए मदुरै नगरपालिका स्वास्थ्य विभाग को स्वचालित अलर्ट भेजें।',
        alertHealth: 'मदुरै स्वास्थ्य विभाग को अलर्ट करें',
        alertDispatched: 'स्वास्थ्य विभाग को अलर्ट भेजा गया',
        dengueZones: 'डेंगू क्षेत्र',
        malariaZone: 'मलेरिया क्षेत्र',

        totalItems: 'कुल आइटम',
        critical: 'गंभीर',
        lowStock: 'कम स्टॉक',
        inventoryValue: 'इन्वेंटरी मूल्य',
        bioSupplyRegistry: 'बायो-सप्लाई चेन रजिस्ट्री',
        autoReorderNote: '<20% क्षमता पर ऑटो-रीऑर्डर',
        material: 'सामग्री',
        category: 'श्रेणी',
        stockLevel: 'स्टॉक स्तर',
        status: 'स्थिति',
        supplier: 'आपूर्तिकर्ता',
        action: 'कार्रवाई',
        autoReorder: 'ऑटो-रीऑर्डर',
        ordered: 'ऑर्डर किया गया',
        processing: 'प्रोसेसिंग...',

        langRegion: 'भाषा & क्षेत्र',
        langDesc: 'प्लेटफ़ॉर्म इंटरफ़ेस की डिस्प्ले भाषा चुनें',
        appearance: 'दिखावट',
        appearanceDesc: 'अपने डैशबोर्ड की विज़ुअल थीम कस्टमाइज़ करें',
        userProfile: 'उपयोगकर्ता प्रोफ़ाइल',
        profileDesc: 'आपके व्यक्तिगत और संगठनात्मक विवरण',
        editProfile: 'प्रोफ़ाइल संपादित करें',
        saveChanges: 'परिवर्तन सहेजें',
        fullName: 'पूरा नाम',
        designation: 'पदनाम',
        emailAddress: 'ईमेल पता',
        phoneNumber: 'फोन नंबर',
        department: 'विभाग',
        location: 'स्थान',
        notifications: 'सूचनाएं',
        notifDesc: 'अलर्ट और अपडेट कैसे प्राप्त करें',
        emailNotif: 'ईमेल सूचनाएं',
        emailNotifDesc: 'ईमेल के माध्यम से दैनिक सारांश और महत्वपूर्ण अलर्ट प्राप्त करें',
        smsAlerts: 'SMS अलर्ट',
        smsAlertsDesc: 'उच्च-प्राथमिकता चेतावनियों के लिए टेक्स्ट संदेश प्राप्त करें',
        browserPush: 'ब्राउज़र पुश',
        browserPushDesc: 'रीयल-टाइम ब्राउज़र पुश नोटिफिकेशन',
        healthAlerts: 'स्वास्थ्य विभाग अलर्ट',
        healthAlertsDesc: 'मदुरै नगरपालिका स्वास्थ्य विभाग को स्वचालित अग्रेषण',
        loginSecurity: 'लॉगिन & सुरक्षा',
        loginSecDesc: 'खाता पहुंच और प्रमाणीकरण सेटिंग्स',
        password: 'पासवर्ड',
        passwordDesc: '14 दिन पहले बदला गया',
        change: 'बदलें',
        twoFactor: 'टू-फैक्टर ऑथेंटिकेशन',
        twoFactorDesc: 'अपने खाते में सुरक्षा की अतिरिक्त परत जोड़ें',
        enabled: 'सक्षम',
        activeSessions: 'सक्रिय सत्र',
        activeSessionsDesc: 'इस डिवाइस पर 1 सक्रिय सत्र',
        loginHistory: 'लॉगिन इतिहास',
        loginHistoryDesc: 'अंतिम लॉगिन: आज 18:46 IST मदुरै से',
        viewAll: 'सभी देखें',
        signOut: 'सभी डिवाइस से साइन आउट करें',
    }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('en');

    const t = (key) => {
        return translations[lang]?.[key] || translations['en']?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
    return context;
}
